# This is a basic workflow to help you get started with Actions

name: jira CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  api:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.18.2'

    - name: Install npm dependencies and build typescript
      run: |
        cd api/
        npm ci
        npx typescript

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_PRIVATE_KEY }} # The keys should be generated using the PEM format.eg: ssh-keygen -m PEM -t rsa -b 4096
          ARGS: '--delete'
          SOURCE: api/
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          TARGET: ${{ secrets.SERVER_ROOT }}/_api/jira

  client:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.18.2'

    - name: Install npm dependencies
      run: |
        cd client
        npm ci

    - name: Run build task
      run: npm run build

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_PRIVATE_KEY }} # The keys should be generated using the PEM format.eg: ssh-keygen -m PEM -t rsa -b 4096
          ARGS: '--delete'
          SOURCE: client/build/
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          TARGET: ${{ secrets.SERVER_ROOT }}/yinpo.space/jira
          EXCLUDE: "/dist, /node_modules, /build"
